services:
  server:
    container_name: qtsseum-grpc-server
    build:
      context: .
      dockerfile: Dockerfile
    image: qt-grpc-dev:latest
    working_dir: /workspace
    depends_on:
      - db
    volumes:
      - .:/workspace
      - build-cache:/workspace/build
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "50051:50051"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  client:
    container_name: qtsseum-client-app
    image: qt-grpc-dev:latest
    working_dir: /workspace
    depends_on:
      - server
    volumes:
      - .:/workspace
      - build-cache:/workspace/build
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:${XAUTHORITY}
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    stdin_open: true
    tty: true
    command: bash

  db:
    container_name: qtsseum-postgres
    image: postgres:18
    restart: always
    env_file: .env.example
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    container_name: qtsseum-pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file: .env.example
    ports:
      - "5050:80"

volumes:
  db:
    driver: local
  build-cache: